Add yml linter
+fix ini linter.

We can't use  because the return code of
bash command will not be the return code of find.

We need to use yamllint one file at a time because the log of
Github Actions drop the name of the yaml file with problem :

Error: [new-lines] wrong new line character: expected \r\n

Update from bansan85/ocr-book@fde233c8ec2021f59b2d8f2a3557a985d9f8fa3d